services:
  web:
    build: .
    image: php:8.4-apache
    container_name: php-apache-test
    ports:
      - "8080:80" # Apache accessible sur localhost:8080
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE= < Insérer le nom de votre base de donnée >
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: mysql-db-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: < Insérer le nom de votre base de donnée >
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
      - ./db/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-test
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M 
    ports:
      - "8081:80" # Port changé pour éviter conflit
    depends_on:
      - db

volumes:
  db_data:
